### ISSUE TITLE
Update bio

### ISSUE THREAD

**Issue by chrismerritt** [chrismerritt/chris-merritt#23]
Update bio to : 

Chris Merritt is the chief product officer at N7th, managing director at Faculty, and the managing partner at  Atlas Local in Greenville, South Carolina.

 or....

Thought? Should we just stack those now that there are so many of them? Open to your thoughts :) 

Ex:

Chris Merritt is... 
chief product officer at [N7th](https://n7th.com)
managing director at Faculty
managing partner at  Atlas Local 

in Greenville, South Carolina.

Thanks pal :)

**Comment by xdesro** [comment]
Resolved by b78d19baed3d1259d6cbe5dbb9b24291ca24ec9f!
